### ISSUE TITLE
Отправка результатов при запуске тестов в несколько потоков

### ISSUE THREAD

**Issue by ElUnicornio** [testit-tms/adapters-java#13]
Добрый день. 
Обнаружил что при использовании библиотек testit результаты в прогон отправляются криво. 
Мой стек Selenide 5.25.0 + Junit 5 5.8.2 + Java 11 + Maven 3.0.0-M5
Запускаю через строку Maven в 3 потока. Как итог записываются какие то пустые тест раны, только один не пустой да и в том не все тесты записываются. Из 43 тестов записываются результаты от силы 15. 
Так же запустив в одном потоке результаты записываются нормально. 
Предполагаю что проблема в том как именно формируется Json для отправки на сервер TestIT2
Помогите решить данную проблему.

**Comment by testit-tms** [comment]
Добрый день.
Попробуйте создать тест ран в ручную в системе и указать в конфигурации его ID. Тогда результаты должны будут залиться в этот тест ран.
Просьба предоставить команду, по которой запускаете автотесты.

**Comment by ElUnicornio** [comment]
mvn -Dsite=PPR -Dthread.count=3 -Drerun.count=1 -DisLocal=false -Dgroups=smoke -DexcludedGroups=functional test
Ну не хотелось бы на каждый ран прописывать новый ID рана

**Comment by testit-tms** [comment]
Добавили поддержку параллельного запуска в версии 0.1.2
