### ISSUE TITLE
Получение параметров из env не работает с версии 2.3.3

### ISSUE THREAD

**Issue by Alexxx221** [testit-tms/adapters-java#154]
Добрый день.

Начиная с версии 2.3.3 в классе `ru.testit.properties.AppProperties` библиотеки `testit-java-commons` некорректно реализовано получение env параметров.

А именно в методе `loadProperties()`, есть такие строчки:
```
properties.putAll(loadPropertiesFromEnv(envVarsNames.getOrDefault("env", new HashMap<>())));
properties.putAll(loadPropertiesFromEnv(envVarsNames.getOrDefault("cli", new HashMap<>())));
```

При этом реализация метода `loadPropertiesFromEnv()` содержит получение только системных properties: 
`Properties properties = System.getProperties();`

Получение переменных среды через `System.getEnv()` отсутствует.

**Comment by komissarov-petr** [comment]
Fixed https://github.com/testit-tms/adapters-java/pull/155
