### ISSUE TITLE
Сompatibility with Citrus Framework

### ISSUE THREAD

**Issue by L1nstat** [testit-tms/adapters-java#31]
Hi.
I tryed to use adapters-java 0.2.2 in my project with TestNG 7.5 + Citrus 2.8.0 + Maven and test results didn't send to Test it server, when i run project on my machine.
But test run started and closed succesfilly.
In logs i seen that:

ERROR HttpWriter:118 - Can not write the class: {"errors":{"Setup[0].Title":["The Title field is required."],"Setup[1].Title":["The Title field is required."],"Setup[2].Title":["The Title field is required."],"Teardown[0].Title":["The Title field is required."]},"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"00-3472514e4c44df20827c0bd1faa59d6b-fec6aeb3c7f9b696-00"}

I figured out that the problem is this: 
My test classes as citrus tests extends TestNGCitrusTestRunner. It extends TestNGCitrusTest, then AbstractTestNGCitrusTest and finally AbstractTestNGSpringContextTests.
This class has methods wich annotated as 
org.testng.annotations.AfterClass;
org.testng.annotations.AfterMethod;
org.testng.annotations.BeforeClass;
org.testng.annotations.BeforeMethod;
BaseTestNgListener sees it and perceives as steps without title and sets to container's lists beforeEachTest and so on.

I resolve it by Overriding AbstractTestNGSpringContextTests's methods and add Title annotations to it but i think must be more elegant solution:)

**Comment by testit-tms** [comment]
Hi.
Can you provide an example project?
We will research this problem and try to fix it

**Comment by L1nstat** [comment]
ofc.
https://github.com/L1nstat/CitrusTestExample.git

**Comment by testit-tms** [comment]
We have released a new version 1.0.0
It contains fixes for your problem

**Comment by L1nstat** [comment]
Thank you, this problem was resolved.
But another one emerged.
Citrus tests means use the citrus context. It is injecting on method level by use TestNg annotation @Parameters and writing to arguments, for example:
@Parameters(value = {"testContext"})
public void example(@Optional @CitrusResource TestContext testContext)

When i use it i get an error:
java.lang.NullPointerException
	at ru.testit.listener.BaseTestNgListener.getParameters(BaseTestNgListener.java:153)
	at ru.testit.listener.BaseTestNgListener.startTestCase(BaseTestNgListener.java:97)
	at ru.testit.listener.BaseTestNgListener.onTestStart(BaseTestNgListener.java:87)
	at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:106)
	at org.testng.internal.invokers.TestInvoker.runTestResultListener(TestInvoker.java:276)

So adapter doesn't see this param when getting params from test result.
I updated example project https://github.com/L1nstat/CitrusTestExample.git
Is it a new issue?

**Comment by testit-tms** [comment]
Yes, this is a new issue. We will look into your issue
