### ISSUE TITLE
Адаптер(слушатель) для Cucumber Java

### ISSUE THREAD

**Issue by BAMTIUIP** [testit-tms/adapters-java#44]
Хотелось бы увидеть готового слушателя для кукумбера, в пропертях tms.enable true тогда работает, false, не взаимодействуем с тмс, чтобы данные автоматически обновлялись из указанных в пропертях, запустил пачку фич с тестами, если тест ран указан- обновляются статусы существующих тестов в ране, и добавляются новые если их не было в ране, не запущенные тесты содержащиеся в ране не как не обновляются, если в пропертях стоит параметр closeRun, то при успешном прогоне всех тестов, ран закрывается, если из пропертей id рана не существует в проекте - создать новый ран

**Comment by testit-tms** [comment]
Привет! Какая версия кукумбера интересует?

**Comment by BAMTIUIP** [comment]
Cucumber 6.11.0

**Comment by BAMTIUIP** [comment]
> Привет! Какая версия кукумбера интересует?

6.11.0

**Comment by BAMTIUIP** [comment]
> Можете использовать адаптер testit-adapter-cucumber6:1.1.1: https://github.com/testit-tms/adapters-java/tree/main/testit-adapter-cucumber6

А как настроить cucumberRunner в папке  если мы используем junit6 у вас в примере используется extends AbstractTestNGCucumberTests? Также если воспользоваться прям из адаптера cucumber6 попытаться пример запустить со своими пропертями где такого тест кейса не существует в тестит т.е рандомное название кейса и фичи то вылазит ошибка error ru.testit.services.AdapterManager - Could not update test case: no test case running при этом при аналогичном сценарии если запускать тесты из адаптера junit6 то данные тест кейсы заводятся в проекте как новые и все ок

**Comment by BAMTIUIP** [comment]
> > Можете использовать адаптер testit-adapter-cucumber6:1.1.1: https://github.com/testit-tms/adapters-java/tree/main/testit-adapter-cucumber6
> 
> А как настроить cucumberRunner в папке если мы используем junit6 у вас в примере используется extends AbstractTestNGCucumberTests? Также если воспользоваться прям из адаптера cucumber6 попытаться пример запустить со своими пропертями где такого тест кейса не существует в тестит т.е рандомное название кейса и фичи то вылазит ошибка error ru.testit.services.AdapterManager - Could not update test case: no test case running при этом при аналогичном сценарии если запускать тесты из адаптера junit6 то данные тест кейсы заводятся в проекте как новые и все ок

В общем я ваш адаптер cucumber6 выпилил к себе в проект чуть доработал на junit6 и все завелось отправка проходит без проблем

**Comment by testit-tms** [comment]
Мы не поддерживаем junit6. Хорошо, что у вас все заработало
