### ISSUE TITLE
Не выгружаются результаты при параллельном запуске тестов

### ISSUE THREAD

**Issue by tmaxim2** [testit-tms/adapters-java#51]
Добрый день.
При параллельном выполнении тестов  в Test IT выгружается результат только одного для каждого класса. У остальных в консоли выводятся ошибки

[ForkJoinPool-1-worker-5] ERROR ru.testit.services.AdapterManager - Could not update class container: container with uuid 954091bb-b72e-4569-9a78-d9136ef70758 not found
[ForkJoinPool-1-worker-6] ERROR ru.testit.services.AdapterManager - Could not update class container: container with uuid 44a493ff-a69e-48d8-a8af-3fceeb9f50f9 not found

Использовал testit-adapter-junit5
Параллельный запуск включил аннотацией @Execution(ExecutionMode.CONCURRENT) и junit.jupiter.execution.parallel.enabled=true

**Comment by testit-tms** [comment]
Добрый день! Можете прислать тестовый проект, в котором возникает проблема?

**Comment by tmaxim2** [comment]
[untitled.zip](https://github.com/testit-tms/adapters-java/files/9699416/untitled.zip)

**Comment by testit-tms** [comment]
Попробуйте версию 1.1.1
