### ISSUE TITLE
Не отправляется вложение при расширении AfterEachCallback

### ISSUE THREAD

**Issue by ElUnicornio** [testit-tms/adapters-java#54]
Хочу настроить отправку скриншота после падения теста в виде вложения через Adapter. Расширение класса AfterEachCallback не срабатывает.
```
public class ScreenShootExt implements AfterEachCallback {
    @Override
    public void afterEach(ExtensionContext extensionContext) {
        extensionContext.getExecutionException().ifPresent(error -> {
            Adapter.addAttachments(Screenshots.takeScreenShotAsFile().getPath());
        });
        Screenshots.finishContext();
    }
}
```
Были попытки просто используя аннотации AfterEach прокинуть вложения. Но Такое простое решение при многопточном запуске рушится само собой. 
Стек: Java 11+Junit 5 + Selenide

**Comment by testit-tms** [comment]
Привет! 
Наш адаптер не поддерживает класс AfterEachCallback. 
Можете подробнее объяснить проблему при использовании AfterEach и предоставить тестовый проект с проблемой?

**Comment by testit-tms** [comment]
Какой тестовый фреймворк используете?

**Comment by testit-tms** [comment]
Вам нужно, чтоб после падения теста в функции AfterEach была возможность добавить скриншот падения?

**Comment by ElUnicornio** [comment]
Да, но исключительно после падения

**Comment by AMGESHIK** [comment]
Тоже инетерусет каким образом прикрепить скриншот только после падения используя Junit 5 и selenide

**Comment by testit-tms** [comment]
Попробуйте версию 1.1.1. В методе с аннотацией AfterEach добавить прикрепление скриншота в случае необходимости

**Comment by ElUnicornio** [comment]
@testit-tms Не совсем понимаю как это связано. Имеется в виду простой Adapter.addAtachment() в методе с AfterEach работает как надо. Но так он будет отправлять скриншоты на каждый тест.
Можете прикрепить пример применения?
