### ISSUE TITLE
Добавление вложений после теста

### ISSUE THREAD

**Issue by AMGESHIK** [testit-tms/adapters-java#70]
В документации (https://github.com/testit-tms/adapters-java/tree/main/testit-java-commons)  есть следующее:

After that, you need to add file ru.testit.listener.AdapterListener to resources/META-INT/services folder:
your-package.AttachmentManager

Я понимаю это так: нужно добавить файл AdapterListener в Директорию resources/META-INT/services
Но как это сделать и зачем, мне непонятно.
Мало информации в документации.

Распишите, пожалуйста, более подробно, что нужно в этом пункте сделать, а еще лучше с примером.

**Comment by ElUnicornio** [comment]
Присоединяюсь к вопросу
Создал папку META-INT/services в проекте по пути test/src/java/resources
Добавил туда файл с названием ru.testit.listener.AdapterListener с содержимым util.AttachmentManager (путь где лежит мой класс для скриншотов)
В классе содержится код:
`public class AttachmentManager implements AdapterListener {
    public void beforeTestStop(final TestResult result) {
        if (result.getItemStatus().equals(ItemStatus.FAILED)) {
            // Add a screenshot
            Adapter.addAttachments("Screenshot.jpg",
                    new ByteArrayInputStream(((TakesScreenshot) WebDriverRunner.getWebDriver())
                            .getScreenshotAs(OutputType.BYTES)));;
        }
    }
}`
IDEA показывает что класс используется в файле  ru.testit.listener.AdapterListener, но так же показывает что метод beforeTestStop() не используется.
Как итог скриншоты при провале не отправляются.
Может я что-то упустил?

**Comment by testit-owner** [comment]
Используется стандартный [SPI](https://en.wikipedia.org/wiki/Service_provider_interface) механизм.
Можете посмотреть как он работает, например тут: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/ServiceLoader.html или https://habr.com/ru/post/118488/

Так же добавили в примеры проект, где это реализована загрузка аттачей в случае падения теста: https://github.com/testit-tms/java-examples/tree/main/maven-junit5

**Comment by ElUnicornio** [comment]
Я все сделал как у вас в примере. Даже IDEA начала показывать что мой beforeTestStop начал использоваться. Но к сожалению скриншот так и не приклепяется. Java 11+junit 5+selenide 5.25.0

**Comment by testit-owner** [comment]
Попробуйте при падении теста просто прикрепить текст как файл. 
Например вот так: Adapter.addAttachments("Failed", "screenshot.txt"); 
Если файл так же не прикрепится, то пришлите свой тестовый проект для разбора.

**Comment by AMGESHIK** [comment]
@ElUnicornio Я у себя решил проблему назвав папку в resorces как META-INF, а не META-INT, как об этом указано в документации. Видимо там опечатка
