### ISSUE TITLE
Перестали отправляться результаты

### ISSUE THREAD

**Issue by AMGESHIK** [testit-tms/adapters-java#76]
После обновления адаптера для junit 5 с версии 1.1.9 до 1.2.1 перестали отправляться результаты тестов в TMS testit enterprice  3.5.x. Режим адаптера 0.

**Comment by Support-Agent** [comment]
Попробуйте с зависимостями:
<dependency>
            <groupId>ru.testit</groupId>
            <artifactId>testit-java-commons</artifactId>
            <version>1.1.9</version>
        </dependency>
        <dependency>
            <groupId>ru.testit</groupId>
            <artifactId>testit-adapter-junit5</artifactId>
            <version>1.2.1</version>

должно проливаться
