### ISSUE TITLE
Есть ли возможность отключить интеграцию с TestIT?

### ISSUE THREAD

**Issue by LichieLich** [testit-tms/adapters-java#80]
Хотелось бы знать, есть ли возможность отключить интеграцию с TestIT? Например, я хочу в локальном окружении отлаживать работу автотестов и при этом не отправлять ничего в TestIT.  Насколько я понял, `adapterMode` поддерживает 3 варианта запуска, но все они подразумевают отправку данных в ТМС.

**Comment by Wanyann** [comment]
Присоединяюсь к вопросу. Возможность не отправлять результаты во время отладки была бы очень кстати.

**Comment by TatianaKlimova91** [comment]
Можно попробовать отключить listener и запускать тесты локально

**Comment by LichieLich** [comment]
Можно какой-нибудь пример, как это сделать, пожалуйста?

**Comment by AlekseiSuzume** [comment]
Есть ли рабочее решение по вопросу?

**Comment by komissarov-petr** [comment]
Добрый день, в адаптер уже добавлен параметр [testit](https://github.com/testit-tms/adapters-java/tree/main/testit-adapter-junit5#configuration), который включает/отключает интеграцию, начиная с версии [1.6.2](https://github.com/testit-tms/adapters-java/releases/tag/1.6.2). Мы рекомендуем обновится до последней поддерживаемой версии адаптера.

**Comment by IsakovEI** [comment]
> Добрый день, в адаптер уже добавлен параметр [testit](https://github.com/testit-tms/adapters-java/tree/main/testit-adapter-junit5#configuration), который включает/отключает интеграцию, начиная с версии [1.6.2](https://github.com/testit-tms/adapters-java/releases/tag/1.6.2). Мы рекомендуем обновится до последней поддерживаемой версии адаптера.

Если я все правильно понял, то в инструкции написано использовать переменную testIt в testit.properties для включения или отключения отправки отчетов. Она не работает. Вместо нее нужно использовать tmsTestIt. Тогда сообщение перестает отправляться. Но к нему по прежнему пытаются присоединиться аттачи.

**Comment by komissarov-petr** [comment]
Список параметров актуализирован: https://github.com/testit-tms/adapters-java/tree/main/testit-adapter-junit5#configuration
Валидация параметров отключена если и только если выключена интеграция с Test IT.
https://github.com/testit-tms/adapters-java/releases/tag/2.3.1

**Comment by AlekseiSuzume** [comment]
> Список параметров актуализирован: https://github.com/testit-tms/adapters-java/tree/main/testit-adapter-junit5#configuration Валидация параметров отключена если и только если выключена интеграция с Test IT. https://github.com/testit-tms/adapters-java/releases/tag/2.3.2

Добрый день. Очень нужная фича, но тесты перестают запускаться на версиях адаптера выше 2.2.10. (Gradle + JUnit5), билд заканчивается без ошибок, но тесты при этом не стартуют.

**Comment by komissarov-petr** [comment]
@AlekseiSuzume обновите адаптер до последней версии 2.3.3.

**Comment by AlekseiSuzume** [comment]
@komissarov-petr Пробовал все версии с 2.3 и ниже, пока не дошёл до 2.2.10, на которой начали запускаться тесты. Сегодня поднимал версию до 2.3.3, но результат тот же - тесты не запускаются.

**Comment by komissarov-petr** [comment]
@AlekseiSuzume таблицу совместимости версий вы можете увидеть https://github.com/testit-tms/adapters-java?tab=readme-ov-file#compatibility То есть адаптеры, начиная с версии 2.3.0, требуют обновления Test IT (самой tms'ки) до версии 5.0.
